---
title: "Motivated Reasoning Experiment"
author: "Matthew Barnfield"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages

```{r warning = F, message = F}
# load libraries
if (!require("pacman")){
  install.packages("pacman")
}
pacman::p_load(knitr,
               tidyverse, 
               ggpubr,
               here,
               emmeans,
               lubridate,
               devtools,
               brms)

install_github("jackobailey/jbmisc")

library(jbmisc)
```

# simulate

``` {r warning = F, message = F}


# simulate likert function (adapted from https://github.com/jackobailey/surveys_bias_econ_percs/blob/main/_scripts/010_power_analysis.R)

sim_likert_party <- 
  function(
    seed = NULL, # random seed
    n = 1500, # sample size
    t = c(-.5, 0, .5, 1), # thresholds
    b = rep(1, 8), # average effects (one per parameter)
    d = rep(0, 8) # effects on variance (one per parameter)
  ){
    
    # Set random seed
    set.seed(seed)
    
    # Simulate dataset
    dta <- 
      tibble(
        treat = rep(c("none", "accuracy", "direction"), each = n/3),
        vote = 
          sample(
            x = c("Non", "Inc", "Opp"),
            replace = T,
            size = n,
            prob = rep(1/3, 3)
          )
      ) %>% 
      mutate(
        inc = vote %>% as_dummy("Inc"),
        opp = vote %>% as_dummy("Opp"),
        acc = treat %>% as_dummy("accuracy"),
        dir = treat %>% as_dummy("direction")
      )
    
    # Compute latent-y location and scale parameters for each individual
    dta <- 
      dta %>% 
      mutate(
        mean =
          b[1]*dta$acc +
          b[2]*dta$dir +
          b[3]*dta$inc +
          b[4]*dta$opp +
          b[5]*(dta$acc*dta$inc) +
          b[6]*(dta$acc*dta$opp) +
          b[7]*(dta$dir*dta$inc) +
          b[8]*(dta$dir*dta$opp),
        sd =
          1/exp(
            d[1]*dta$acc +
            d[2]*dta$dir +
            d[3]*dta$inc +
            d[4]*dta$opp +
            d[5]*(dta$acc*dta$inc) +
            d[6]*(dta$acc*dta$opp) +
            d[7]*(dta$dir*dta$inc) +
            d[8]*(dta$dir*dta$opp)
          )
      )
    
    # Calculate probabilities of each response for each individual
    dta <- 
      dta %>% 
      mutate(
        p1 = pnorm(t[1], mean, sd),
        p2 = pnorm(t[2], mean, sd) - pnorm(t[1], mean, sd),
        p3 = pnorm(t[3], mean, sd) - pnorm(t[2], mean, sd),
        p4 = pnorm(t[4], mean, sd) - pnorm(t[3], mean, sd),
        p5 = 1 - pnorm(t[4], mean, sd)
      )
    
    # For each individual, sample a single response category
    dta <- dta %>% mutate(resp = NA)
    
    for (i in 1:nrow(dta)) {
      dta$resp[i] <- 
        sample(
          x = c(1:5), 
          size = 1, 
          prob = c(dta$p1[i], dta$p2[i], dta$p3[i], dta$p4[i], dta$p5[i])
        )
    }
    
    # Convert resp to ordered
    dta <-
      dta %>% 
      mutate(
        resp = resp %>% ordered(labels = c("Lowest",
                                           "Second-lowest",
                                           "Neutral",
                                           "Second-highest",
                                           "Highest" ))
      )
    
    # Return data frame
    dta %>% select(resp, treat, dir, acc, inc, opp)
    
  }

# generate data
test <- 
  sim_likert_party(
    seed = 666,
    n = 3000,
    b = c(0, 0, 0.5, -0.5, -0.2, 0.15, 0.3, -0.3),
    d = c(0, 0, 0, 0, 0, 0, 0, 0)
  )

sample_n(test, 10)


# fit model to recover effects

fit <- 
  brm(
    formula = 
      bf(resp ~ acc + dir + inc + opp + acc:inc + dir:inc + acc:opp + dir:opp) +
      lf(disc ~ 0 + acc + dir + inc + opp + acc:inc + dir:inc + acc:opp + dir:opp, cmc = F),
    family = cumulative(link = "probit",
                        link_disc = "log"),
    prior = 
      prior(normal(0, 1), class = "Intercept") + 
      prior(normal(0, 0.5), class = "b") +
      prior(normal(0, 0.5), class = "b", dpar = "disc"),
    data = test,
    inits = 0,
    warmup = 250,
    iter = 750,
    chains = 4,
    cores = 54,
    seed = 666,
    file = here("_output", "init")
  )

# how are those effects looking? 
summary(fit) 

```